---
- name: Копирование файла docker-compose.yml
  copy:
    src: docker-compose.yml
    dest: /home/vagrant/

- name: Копирование services
  copy:
    src: services
    dest: /home/vagrant/

- name: Копирование nginx
  copy:
    src: nginx
    dest: /home/vagrant/

- name: Развертывание микросервисного приложения с помощью Docker Compose
  command: docker-compose -f /home/vagrant/docker-compose.yml up -d